---
title: "Homework 1"
author: "Lynn Fan"
date: "01-29-2020"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library("dplyr")
```

## Task 0

These are some examples for checking Armstrong numbers. 
Please remove this portion in your final submission.

```{r starter-examples, results='hold'}
1 ^ 1 == 1
5 ^ 1 == 5
2 ^ 2 + 6 ^ 2 == 26
1 ^ 3 + 5 ^ 3 + 3 ^ 3 == 153
2 ^ 3 + 1 ^ 3 + 0 ^ 3 == 210
```

## Task 1

```{r}
is.armstrong <- function(x, na.rm=FALSE) {
  sumofs = 0
   for (s in x) {
     if (is.na(s)==TRUE) { ##remove cases of NA or NaN
       na.rm = TRUE
     } 
     else if (typeof(s)=="character") {
       message("ERROR:NOT A NUMBER")
     }
     else if (s %% 1 != 0){
       message("ERROR:NOT AN INTEGER")
     }
     else if (s < 1 | s > 999) {
       message("OUT OF RANGE")
     }
     else {
       lengths <- length(split(s,"")) ## number of digits
       for (i in lengths) { ## calculate the sum of squares of the digits
           sumofs = sumofs + as.numeric(s[i])^lengths
           i = i + 1
         }
      if (sumofs == s) {
         message(s," is an Armstrong number")
       }
       else message(s," is not an Armstrong number")
       }
   }
}
 
```


## Task 2

<i>
Be sure to remove chunk option `eval=FALSE` in the below code chunks
once you create function `is.armstrong()`. Do not include this italicized
text in your final submission.
</i>

#### Valid inputs

```{r valid-inputs}
is.armstrong(x = 1)
is.armstrong(x = 153)
is.armstrong(x = 154)
is.armstrong(x = c(153, 154, NA))
is.armstrong(x = c(1, 33, 999))
```

#### Invalid inputs

```{r}
is.armstrong(x = -2)
is.armstrong(x = 1011)
is.armstrong(x = c(pi, 6))
is.armstrong(x = "a")
```

## Task 3

Write-up goes here...
